### PR TITLE
Ensure non-numerical keys with a value of undefined are ignored.

### PR DESCRIPTION
**Pull request by alexjeffburke**

### CODE REVIEW

**Comment by papandreou** [comment]
@alexjeffburke Looking good! Could you add a test that makes sure that a `remove` entry is returned when the subject contains a non-numerical key with a defined value, but the value says it shouldn't via `{ foo: undefined }`?

**Comment by alexjeffburke** [comment]
@papandreou That’s a really good case! Absolutely :)

**Comment by alexjeffburke** [comment]
@papandreou I think I've covered a good deal of the cases now - good catch btw, without an additional little undefined check it wasn't marked for removal.

**Comment by papandreou** [comment]
Released as 3.0.1!

**Pull request merged**
